Create virtualenv with '--never-download'
For upgrades, and some new build configurations, trying to
create a new venv results in the error:

Could not get output from /usr/bin/virtualenv --help: Traceback (most recent call last):
File "/usr/bin/virtualenv", line 6, in <module>
from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

To work around this issue, we do the initial build of the
venv using the CLI with the argument '--never-download'
so that virtualenv just uses the versions of pip, setuptools
and wheel that it already has.

Change-Id: I639bc78d34b640a52c32fa175b12fa958518e999